"""
c4a_numbers.py — Canonical numbers for the C4a deep-dive document (c4a_theory.txt).

Produces all key values needed for the theoretical analysis document:
  - alpha and 1/alpha (CODATA, C4a)
  - The gap in absolute, relative, and ratio form
  - R_s and R_s/alpha (the anisotropy)
  - The Hopf geometric factors
  - QED perturbation scale references
  - Prior art values (Wyler, Eddington)
  - Structural decompositions of the C4a formula

Run: python analysis/c4a_numbers.py
"""

import math

SEP  = "=" * 65
SEP2 = "-" * 65

pi    = math.pi
phi   = (1 + math.sqrt(5)) / 2
sqrt5 = math.sqrt(5)
Rs    = sqrt5 / (4 * pi)

alpha_CODATA = 7.2973525693e-3    # CODATA 2018, relative uncertainty 1.5e-10
alpha_C4a    = sqrt5 * phi / (16 * pi**3)   # = (sqrt5+5)/(32*pi^3)

gap_abs = alpha_C4a - alpha_CODATA
gap_rel = gap_abs / alpha_CODATA

print(SEP)
print("ALPHA — CODATA vs C4a")
print(SEP)
print(f"  alpha_CODATA         = {alpha_CODATA:.13e}")
print(f"  1/alpha_CODATA       = {1/alpha_CODATA:.10f}")
print(f"  alpha_C4a            = {alpha_C4a:.13e}")
print(f"  1/alpha_C4a          = {1/alpha_C4a:.10f}")
print(f"  gap (absolute)       = {gap_abs:+.6e}")
print(f"  gap (relative)       = {gap_rel*100:+.6f}%")
print(f"  |gap| / alpha        = {abs(gap_rel):.6f}  ({abs(gap_rel)*100:.4f}%)")
print()

print(SEP)
print("THE C4a FORMULA — STRUCTURAL DECOMPOSITION")
print(SEP)
print()
print("  C4a: alpha = sqrt(5) * phi / (16 * pi^3)")
print(f"             = (sqrt(5) + 5) / (32 * pi^3)")
print()
print(f"  Verification:")
print(f"    (sqrt5+5)/(32*pi^3) = {(sqrt5+5)/(32*pi**3):.13e}")
print(f"    sqrt5*phi/(16*pi^3) = {sqrt5*phi/(16*pi**3):.13e}  (same)")
print()
print(f"  Factor analysis:")
print(f"    sqrt(5)              = {sqrt5:.10f}")
print(f"    phi = (1+sqrt5)/2    = {phi:.10f}")
print(f"    pi                   = {pi:.10f}")
print(f"    pi^3                 = {pi**3:.10f}")
print(f"    16 * pi^3            = {16*pi**3:.10f}")
print(f"    32 * pi^3            = {32*pi**3:.10f}")
print()
print(f"  Geometric reading (Hopf torus):")
print(f"    4*pi^2  = Hopf major-circuit ratio (L_major / R1, for R2/R1 = 2*pi)")
print(f"            = {4*pi**2:.8f}")
print(f"    phi     = icosahedral symmetry factor (diagonal/edge of icosahedron)")
print(f"            = {phi:.8f}")
print(f"    4*pi^2 / phi  = {4*pi**2/phi:.8f}  (target: R_s/alpha = {Rs/alpha_CODATA:.8f})")
print(f"    Error:        = {(4*pi**2/phi - Rs/alpha_CODATA)/(Rs/alpha_CODATA)*100:+.4f}%")
print()
print(f"  Rs/alpha connects the formula to the medium:")
print(f"    R_s              = sqrt(5)/(4*pi) = {Rs:.10f}")
print(f"    R_s / alpha_CODATA = {Rs/alpha_CODATA:.8f}  (matter/EM anisotropy)")
print(f"    4*pi^2 / phi       = {4*pi**2/phi:.8f}  (Hopf ratio / icosahedral)")
print(f"    These differ by    = {(4*pi**2/phi)/(Rs/alpha_CODATA) - 1:+.6f}  ({((4*pi**2/phi)/(Rs/alpha_CODATA)-1)*100:+.4f}%)")
print()

print(SEP)
print("R_s AND THE ANISOTROPY")
print(SEP)
print()
print(f"  R_s (matter saturation ratio) = sqrt(5)/(4*pi) = {Rs:.10f}")
print(f"  alpha (EM saturation ratio)   = {alpha_CODATA:.10e}")
print(f"  Anisotropy = R_s / alpha       = {Rs/alpha_CODATA:.6f}")
print(f"  Inverse    = alpha / R_s       = {alpha_CODATA/Rs:.8f}")
print()
print(f"  Expressed differently:")
print(f"    R_s = sqrt(5)/(4*pi)")
print(f"    alpha ~= R_s / (4*pi^2/phi)")
print(f"          ~= sqrt(5)/(4*pi) * phi/(4*pi^2)")
print(f"          ~= sqrt(5)*phi / (16*pi^3)")
print(f"    This is C4a. The formula says: alpha = R_s * phi/(4*pi^2)")
print(f"    i.e., alpha is R_s scaled down by the Hopf torus major-circuit")
print(f"    ratio divided by phi.")
print()

print(SEP)
print("QED PERTURBATION SCALE — CONTEXT FOR THE GAP")
print(SEP)
print()
a_schwinger = alpha_CODATA / (2*pi)
a2          = alpha_CODATA**2
a_pi2       = (alpha_CODATA/pi)**2
print(f"  QED series: g/2 = 1 + alpha/(2*pi) + c2*(alpha/pi)^2 + ...")
print()
print(f"  alpha/(2*pi)   = {a_schwinger:.6e}  (Schwinger 1st-order, 0.116%)")
print(f"  alpha^2        = {a2:.6e}  (2nd-order scale)")
print(f"  (alpha/pi)^2   = {a_pi2:.6e}  (2nd-order perturbation)")
print()
print(f"  The gap:  {gap_abs:+.6e}")
print()
print(f"  gap / alpha/(2*pi)  = {gap_abs/a_schwinger:.6f}  (0.38% of Schwinger term)")
print(f"  gap / alpha^2       = {gap_abs/a2:.5f}")
print(f"  gap / (alpha/pi)^2  = {gap_abs/a_pi2:.5f}  <-- closest ratio: ~0.82")
print()
print(f"  Key: the gap is NOT simply N * alpha/(2*pi) for any clean N.")
print(f"  It is approximately 0.82 * (alpha/pi)^2 -- a second-order scale,")
print(f"  but the prefactor 0.82 is not a geometric number.")
print()
print(f"  If alpha = C4a * (1 + c1 * alpha/pi):")
print(f"    c1_needed = {(alpha_CODATA/alpha_C4a - 1) * pi / alpha_CODATA:.6f}")
print(f"    QED c1    = 0.500000 (Schwinger, exact)")
print(f"    ratio     = {(alpha_CODATA/alpha_C4a - 1) * pi / alpha_CODATA / 0.5:.6f}")
print()

print(SEP)
print("PRIOR ART — NUMERICAL COMPARISON")
print(SEP)
print()
wyler = (9 / (8*pi**4)) * (pi**5 / 16 / 120)**0.25
print(f"  CODATA:     alpha = {alpha_CODATA:.13e}   1/alpha = {1/alpha_CODATA:.8f}")
print(f"  Eddington:  1/alpha = 137 exactly  -> alpha = {1/137:.13e}   err = {(1/137-alpha_CODATA)/alpha_CODATA*100:+.4f}%")
print(f"  Wyler:      alpha = {wyler:.13e}   err = {(wyler-alpha_CODATA)/alpha_CODATA*100:+.6f}%  1/alpha = {1/wyler:.6f}")
print(f"  C4a:        alpha = {alpha_C4a:.13e}   err = {gap_rel*100:+.6f}%  1/alpha = {1/alpha_C4a:.6f}")
print()
print(f"  Note on Wyler: achieves {abs((wyler-alpha_CODATA)/alpha_CODATA*100):.4f}% with dimensional")
print(f"  inconsistency (chose SO(5,2)/SO(5) volume ratio ad hoc to fit).")
print(f"  C4a at {abs(gap_rel*100):.4f}% has a stated geometric origin and no ad hoc choices.")
print()

print(SEP)
print("THE GAP AS A FRACTION OF 1/alpha")
print(SEP)
print()
inv_alpha = 1/alpha_CODATA
inv_C4a   = 1/alpha_C4a
gap_inv   = inv_C4a - inv_alpha
print(f"  1/alpha_CODATA = {inv_alpha:.10f}")
print(f"  1/alpha_C4a    = {inv_C4a:.10f}")
print(f"  gap in 1/alpha = {gap_inv:+.8f}  (C4a gives 1/alpha {abs(gap_inv):.4f} too low)")
print()
print(f"  In words: C4a predicts 1/alpha = {inv_C4a:.6f},")
print(f"  CODATA says 1/alpha = {inv_alpha:.6f}.")
print(f"  C4a is low by {abs(gap_inv):.4f} in the 1/alpha representation.")
print(f"  The 'true' denominator needs to be {inv_alpha:.6f}, not {inv_C4a:.6f}.")
print()

print(SEP)
print("HOPF FIBRATION KEY RATIOS")
print(SEP)
print()
print(f"  Hopf fibration: S^1 -> S^3 -> S^2")
print(f"  Fiber:  S^1 (circle)")
print(f"  Total:  S^3 (3-sphere)")
print(f"  Base:   S^2 (2-sphere)")
print(f"  Hopf invariant: H = 1 (for the standard Hopf map)")
print()
print(f"  Torus from Hopf fibration (R2/R1 = 2*pi):")
print(f"    R2/R1            = 2*pi = {2*pi:.8f}")
print(f"    Tube radius R1   = 1 (normalised)")
print(f"    Major radius R2  = 2*pi = {2*pi:.8f}")
print(f"    Major circumference  = 2*pi*R2 = 4*pi^2 = {4*pi**2:.8f}")
print(f"    Minor circumference  = 2*pi*R1 = 2*pi   = {2*pi:.8f}")
print(f"    Ratio major/minor    = R2/R1 = 2*pi      = {2*pi:.8f}")
print(f"    Surface area         = (2*pi*R2)*(2*pi*R1) = 4*pi^2 * 2*pi = {4*pi**2 * 2*pi:.6f}")
print()
print(f"  Icosahedral symmetry:")
print(f"    phi = (1+sqrt5)/2    = {phi:.10f}")
print(f"    phi^2 = phi+1        = {phi**2:.10f}")
print(f"    1/phi = phi-1        = {1/phi:.10f}")
print(f"    Icosahedral rotation group order: 60")
print(f"    Full symmetry group order: 120")
print()
print(f"  The ratio 4*pi^2 / phi = {4*pi**2/phi:.10f}")
print(f"  This equals R_s/alpha to {(4*pi**2/phi - Rs/alpha_CODATA)/(Rs/alpha_CODATA)*100:+.4f}%")
print()

print(SEP)
print("WHAT WOULD MAKE THE GAP EXACTLY ZERO")
print(SEP)
print()
exact_ratio = Rs / alpha_CODATA
print(f"  For C4a to be exact, we need the geometric ratio to equal R_s/alpha exactly.")
print(f"  R_s/alpha       = {exact_ratio:.10f}")
print(f"  4*pi^2/phi      = {4*pi**2/phi:.10f}")
print(f"  The true ratio  = {exact_ratio:.10f}")
print(f"  Difference      = {exact_ratio - 4*pi**2/phi:+.8f}")
print()
print(f"  The exact ratio R_s/alpha can be written as:")
print(f"    sqrt(5)/(4*pi) / alpha = sqrt(5) / (4*pi*alpha)")
print(f"    = {sqrt5} / (4 * {pi:.6f} * {alpha_CODATA:.6e})")
print(f"    = {exact_ratio:.10f}")
print()
print(f"  Question for theorist: is there a topological expression that")
print(f"  evaluates to {exact_ratio:.8f} rather than {4*pi**2/phi:.8f}?")
print(f"  Difference is {exact_ratio - 4*pi**2/phi:+.8f} ({(exact_ratio - 4*pi**2/phi)/(4*pi**2/phi)*100:+.4f}%).")
print()
print(f"  Equivalently: what geometric quantity Q satisfies alpha = R_s/Q exactly?")
print(f"  Q_exact = R_s/alpha = {exact_ratio:.10f}")
print(f"  Q_C4a   = 4*pi^2/phi = {4*pi**2/phi:.10f}")
print(f"  Q_exact - Q_C4a = {exact_ratio - 4*pi**2/phi:+.8f}")
print()
